# -*- coding: utf-8 -*-

import base64
# Form implementation generated from reading ui file 'AccoutingSystemUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from io import BytesIO

from PIL import Image
from PyQt5 import QtCore, QtGui, QtWidgets

from ButtonIcon_jpg import img


class Ui_mainWindows(object):
    def setupUi(self, mainWindows):
        mainWindows.setObjectName("mainWindows")
        mainWindows.resize(743, 650)
        font = QtGui.QFont()
        font.setPointSize(12)
        mainWindows.setFont(font)
        mainWindows.setStyleSheet("background-color: rgb(246, 246, 246);")
        self.sheetInput1 = QtWidgets.QPushButton(mainWindows)
        self.sheetInput1.setGeometry(QtCore.QRect(0, 60, 371, 491))
        self.sheetInput1.setStyleSheet("border:none;")
        self.sheetInput1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(Image.open(BytesIO(base64.b64decode(img))).toqpixmap())
        self.sheetInput1.setIcon(icon)
        self.sheetInput1.setIconSize(QtCore.QSize(512, 512))
        self.sheetInput1.setObjectName("sheetInput1")
        self.sheetInput2 = QtWidgets.QPushButton(mainWindows)
        self.sheetInput2.setGeometry(QtCore.QRect(373, 60, 371, 491))
        self.sheetInput2.setStyleSheet("border:none;")
        self.sheetInput2.setText("")
        self.sheetInput2.setIcon(icon)
        self.sheetInput2.setIconSize(QtCore.QSize(512, 512))
        self.sheetInput2.setObjectName("sheetInput2")
        self.text1 = QtWidgets.QTextBrowser(mainWindows)
        self.text1.setGeometry(QtCore.QRect(0, 0, 371, 61))
        self.text1.setAutoFillBackground(True)
        self.text1.setStyleSheet("border:none;\n"
                                 "background-color: rgb(246, 246, 246);")
        self.text1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text1.setObjectName("text1")
        self.text2 = QtWidgets.QTextBrowser(mainWindows)
        self.text2.setGeometry(QtCore.QRect(373, 0, 371, 61))
        self.text2.setStyleSheet("border:none;\n"
                                 "background-color: rgb(246, 246, 246);")
        self.text2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text2.setObjectName("text2")
        self.line1 = QtWidgets.QFrame(mainWindows)
        self.line1.setGeometry(QtCore.QRect(371, 0, 2, 552))
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.generateOutput = QtWidgets.QPushButton(mainWindows)
        self.generateOutput.setGeometry(QtCore.QRect(0, 553, 743, 97))
        self.generateOutput.setStyleSheet(
            "border:none;font: 36pt \"Adobe Devanagari\";")
        self.generateOutput.setObjectName("generateOutput")
        self.line2 = QtWidgets.QFrame(mainWindows)
        self.line2.setGeometry(QtCore.QRect(0, 552, 743, 2))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")

        self.retranslateUi(mainWindows)
        QtCore.QMetaObject.connectSlotsByName(mainWindows)

    def retranslateUi(self, mainWindows):
        _translate = QtCore.QCoreApplication.translate
        mainWindows.setWindowTitle(_translate("mainWindows", "轮岗绩效核算系统"))
        self.text1.setHtml(_translate("mainWindows", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                      "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">导入员工表</span></p></body></html>"))
        self.text2.setHtml(_translate("mainWindows", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                      "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">导入金额表</span></p></body></html>"))
        self.generateOutput.setText(_translate("mainWindows", "生成表格"))
        self.generateOutput.setShortcut(_translate("mainWindows", "Return"))
